/* ─────────────────────────────────────────
   MediRemind — diseases.js
   Offline database: 80+ diseases & symptoms
   Used when device is offline.
   Gemini AI is used as fallback when online.
───────────────────────────────────────── */

const DISEASE_DB = [
  /* ── COMMON ── */
  { name:'Fever', aliases:['fever','high temperature','pyrexia','temperature','febrile','hot body'], emoji:'🌡️', type:'common', description:'A temporary rise in body temperature, usually a sign your body is fighting an infection. Normal body temperature is around 98.6°F (37°C).', symptoms:['Body temperature above 100.4°F (38°C)','Chills and shivering','Sweating','Headache','Muscle aches','Loss of appetite','Fatigue'], causes:['Viral or bacterial infections','Heat exhaustion','Certain medications','Inflammatory conditions','Teething in infants'], homecare:['Drink plenty of fluids — water, ORS, coconut water','Rest and stay in a cool room','Take paracetamol for high fever','Wear light clothing','Apply damp cloth on forehead'], whenToSeeDoctor:'Fever above 103°F (39.4°C), lasting more than 3 days, seizures, stiff neck, or any fever in a child under 3 months.', urgency:'medium' },

  { name:'Common Cold & Flu', aliases:['cold','flu','influenza','runny nose','sneezing','sore throat','congestion','nasal','blocked nose','rhinitis'], emoji:'🤧', type:'common', description:'A viral infection of the upper respiratory tract. Very common, especially during season changes. Flu is more severe with sudden onset.', symptoms:['Runny or stuffy nose','Sneezing','Sore throat','Cough','Mild fever','Body aches','Fatigue'], causes:['Rhinovirus (cold)','Influenza virus (flu)','Close contact with infected person','Cold dry weather'], homecare:['Rest and sleep well','Drink warm fluids — ginger tea, warm water, soups','Steam inhalation for congestion','Honey and lemon for sore throat','OTC cold medicine for relief'], whenToSeeDoctor:'High fever above 103°F, difficulty breathing, symptoms lasting more than 10 days, chest pain, or persistent vomiting.', urgency:'low' },

  { name:'Headache', aliases:['headache','head pain','head ache','tension headache','pressure in head'], emoji:'😣', type:'common', description:'Headaches are extremely common and usually not serious. Tension headaches are the most common — a dull aching pain around the head.', symptoms:['Dull or throbbing pain','Pressure around forehead or sides','Neck and shoulder stiffness','Sensitivity to light or sound'], causes:['Stress and tension','Dehydration','Skipping meals','Eye strain from screens','Poor posture','Lack of sleep','Caffeine withdrawal'], homecare:['Drink a glass of water first','Rest in a quiet dark room','Apply cold or warm compress','Take paracetamol','Reduce screen time','Gentle neck stretches'], whenToSeeDoctor:'Sudden severe "worst headache of your life", headache with fever and stiff neck, after a head injury, or recurring daily headaches.', urgency:'low' },

  { name:'Back Pain', aliases:['back pain','backache','lower back','spine pain','lumbar pain','slip disc','sciatica','back ache'], emoji:'🦴', type:'common', description:'One of the most common causes of disability. Most cases are mechanical (muscle strain) and resolve with rest and gentle exercise.', symptoms:['Pain in lower, middle, or upper back','Stiffness when standing up','Pain radiating down the leg (sciatica)','Muscle spasms','Difficulty standing straight'], causes:['Poor posture while sitting or standing','Heavy lifting or sudden movements','Muscle strain or sprain','Sedentary lifestyle','Obesity','Slip disc or sciatica'], homecare:['Apply ice for first 48 hours then heat','OTC pain relievers','Gentle stretching and walking','Avoid prolonged bed rest','Correct sitting posture','Strengthen core muscles'], whenToSeeDoctor:'Pain radiating down legs, numbness or tingling, loss of bladder or bowel control, pain after injury, or no improvement after 2 weeks.', urgency:'medium' },

  { name:'Acidity & GERD', aliases:['acidity','acid reflux','heartburn','gerd','stomach acid','burning chest','indigestion','gas trouble','bloating'], emoji:'🔥', type:'common', description:'Acidity happens when stomach acid flows back into the esophagus. GERD is the chronic form. Very common due to spicy and oily food habits.', symptoms:['Burning sensation in chest (heartburn)','Sour or bitter taste in mouth','Regurgitation of food or acid','Nausea','Bloating','Difficulty swallowing','Chronic cough'], causes:['Spicy, oily, or acidic foods','Overeating and eating late at night','Caffeine, alcohol, and carbonated drinks','Lying down immediately after eating','Obesity'], homecare:['Eat small frequent meals','Avoid spicy and oily food','Do not lie down for 2-3 hours after eating','Elevate head while sleeping','Cold milk or coconut water can help','Antacids for quick relief'], whenToSeeDoctor:'Symptoms more than twice a week, difficulty swallowing, blood in stool or vomit, unexplained weight loss, or antacids stop working.', urgency:'medium' },

  { name:'Allergy', aliases:['allergy','allergic reaction','allergic','itching','hives','rash','urticaria','sneezing allergy','dust allergy','pollen allergy','food allergy','skin allergy','allergies'], emoji:'🌿', type:'common', description:'An allergy is an immune system reaction to a normally harmless substance (allergen). Allergies can affect the skin, eyes, nose, lungs, and digestive system.', symptoms:['Sneezing and runny nose','Itchy, watery, or red eyes','Skin rash or hives','Itching (skin, eyes, nose, throat)','Swelling of lips, tongue, or face','Nasal congestion','Coughing or wheezing'], causes:['Pollen, dust mites, pet dander','Certain foods (peanuts, shellfish, milk, eggs)','Insect stings','Medications (aspirin, penicillin)','Mold spores','Latex'], homecare:['Avoid known allergens','Antihistamine tablets for mild reactions','Apply calamine lotion or cold compress for skin rash','Wear a mask in dusty or polluted environments','Keep windows closed during high pollen season','Use air purifiers at home'], whenToSeeDoctor:'Severe reaction (anaphylaxis): difficulty breathing, swelling of throat, rapid heartbeat, dizziness — call emergency immediately. See an allergist for persistent or severe allergies.', urgency:'medium' },

  { name:'Conjunctivitis (Pink Eye)', aliases:['pink eye','conjunctivitis','red eye','eye infection','eye discharge','sticky eye'], emoji:'👁️', type:'common', description:'Inflammation of the outer membrane of the eye (conjunctiva). Can be caused by bacteria, viruses, or allergies. Very contagious if infectious.', symptoms:['Redness in the white of the eye','Discharge (watery or thick yellow/green)','Crusty eyelids especially after sleep','Itching or burning sensation','Sensitivity to light','Blurred vision'], causes:['Bacterial infection','Viral infection (often with common cold)','Allergic reaction','Chemical or smoke irritation'], homecare:['Clean discharge with clean damp cotton','Use prescribed eye drops if bacterial','Avoid touching eyes and wash hands frequently','Avoid sharing towels or eye products','Cool compress for relief'], whenToSeeDoctor:'Vision changes, severe pain, intense redness, symptoms not improving after 3 days, or if a newborn has eye discharge.', urgency:'medium' },

  { name:'Stomach Pain', aliases:['stomach pain','stomach ache','abdominal pain','tummy pain','belly pain','cramps','gastric pain'], emoji:'🤢', type:'common', description:'Stomach or abdominal pain is very common and can range from mild indigestion to serious conditions. Most cases are minor and resolve on their own.', symptoms:['Pain or cramps in the abdomen','Nausea','Bloating and gas','Diarrhea or constipation','Loss of appetite'], causes:['Indigestion or gas','Food poisoning','Constipation','Menstrual cramps','Gastroenteritis (stomach flu)','Ulcers'], homecare:['Rest and avoid solid food for a few hours','Drink clear fluids — water and ORS','Avoid spicy, fatty, or rich foods','Apply warm compress on abdomen','Antacids if burning or acidity'], whenToSeeDoctor:'Severe sudden pain, pain with fever above 101°F, blood in stool or vomit, pain lasting more than 3 days, or inability to keep fluids down.', urgency:'medium' },

  { name:'Diarrhea', aliases:['diarrhea','loose stools','loose motions','watery stool','stomach upset','gastroenteritis','food poisoning'], emoji:'🚽', type:'common', description:'Frequent loose or watery bowel movements. Usually caused by infection, food poisoning, or intolerance. Dehydration is the main risk.', symptoms:['Loose or watery stools 3+ times per day','Stomach cramps','Nausea and vomiting','Fever','Bloating','Urgent need to use bathroom'], causes:['Viral or bacterial infection','Food poisoning','Contaminated water','Lactose intolerance','IBS','Antibiotics side effect'], homecare:['Drink ORS frequently to replace fluids','Eat bland food — banana, rice, boiled potatoes, toast (BRAT diet)','Avoid dairy, spicy, and fatty foods','Rest','Probiotics like curd (yogurt) can help'], whenToSeeDoctor:'Bloody stool, fever above 102°F, symptoms in children under 2, signs of dehydration (no urination, dry mouth, dizziness), or diarrhea lasting more than 3 days.', urgency:'medium' },

  { name:'Constipation', aliases:['constipation','hard stool','no motion','difficulty passing stool','bowel issue'], emoji:'😣', type:'common', description:'Having fewer than 3 bowel movements per week, or stools that are hard and difficult to pass. Very common and usually easily treatable.', symptoms:['Fewer than 3 bowel movements per week','Hard, dry, or lumpy stools','Straining during bowel movements','Feeling of blockage','Bloating and discomfort'], causes:['Low fiber diet','Not drinking enough water','Sedentary lifestyle','Ignoring the urge to go','Certain medications (iron, calcium, antacids)','Stress'], homecare:['Drink 8-10 glasses of water daily','Eat high-fiber foods — fruits, vegetables, whole grains, pulses','Exercise daily — even a 30 min walk helps','Do not ignore the urge to go','Warm water with lemon in the morning'], whenToSeeDoctor:'Constipation lasting more than 3 weeks, blood in stool, unexplained weight loss, severe abdominal pain, or alternating with diarrhea.', urgency:'low' },

  { name:'Nausea & Vomiting', aliases:['nausea','vomiting','feeling sick','throwing up','motion sickness','morning sickness'], emoji:'🤮', type:'common', description:'Nausea is the feeling of wanting to vomit. It can be caused by many conditions from mild (motion sickness) to serious (food poisoning, pregnancy).', symptoms:['Uncomfortable sensation in stomach','Urge to vomit','Actual vomiting','Dizziness','Loss of appetite','Sweating or pale skin'], causes:['Motion sickness','Food poisoning','Pregnancy (morning sickness)','Migraine','Certain medications','Anxiety or stress','Viral infection'], homecare:['Sip clear fluids slowly — water, ginger tea, ORS','Eat small bland meals when able (crackers, toast, banana)','Rest in a comfortable position','Ginger — tea, candies, or capsules can help','Avoid strong smells, greasy or spicy food'], whenToSeeDoctor:'Vomiting blood, severe abdominal pain, signs of dehydration, vomiting for more than 24 hours, or if a child cannot keep any fluids down.', urgency:'medium' },

  /* ── CHRONIC ── */
  { name:'Diabetes', aliases:['diabetes','diabetes mellitus','blood sugar','high sugar','type 1 diabetes','type 2 diabetes','diabetic','insulin resistance','sugar disease'], emoji:'🩸', type:'chronic', description:'A chronic condition where the body cannot properly regulate blood sugar (glucose). Type 1 is autoimmune; Type 2 is lifestyle-related. Both require ongoing management.', symptoms:['Frequent urination','Excessive thirst','Unexplained weight loss','Fatigue and weakness','Blurred vision','Slow-healing wounds','Tingling in hands and feet'], causes:['Insulin resistance (Type 2)','Autoimmune destruction of beta cells (Type 1)','Obesity and sedentary lifestyle','Genetic factors','Poor diet high in refined carbohydrates'], homecare:['Monitor blood glucose regularly','Follow a low-glycemic diet (avoid white rice, sugar, maida)','Exercise 30 minutes daily (walking, yoga)','Take medications as prescribed','Maintain a healthy weight'], whenToSeeDoctor:'If you notice any symptoms, or if blood sugar is consistently above 180 mg/dL after meals or below 70 mg/dL. Routine checkups every 3-6 months.', urgency:'high' },

  { name:'Hypertension', aliases:['high blood pressure','hypertension','blood pressure','bp','hbp','high bp'], emoji:'❤️', type:'chronic', description:'Blood pressure above 130/80 mmHg that puts strain on the heart and blood vessels. Called the "silent killer" because it often has no symptoms until severe.', symptoms:['Usually no symptoms','Headaches in severe cases','Dizziness','Shortness of breath','Nosebleeds (in crisis)','Blurred vision'], causes:['High salt diet','Obesity and lack of exercise','Smoking and alcohol','Stress','Family history','Kidney disease'], homecare:['Reduce salt intake (less than 5g per day)','Exercise regularly — 30 min walks daily','Quit smoking and limit alcohol','Manage stress with yoga or meditation','Monitor BP at home','Take medications as prescribed'], whenToSeeDoctor:'BP consistently above 140/90, severe headache with vision changes, chest pain, or sudden confusion — these are emergency signs.', urgency:'high' },

  { name:'Asthma', aliases:['asthma','breathing problem','wheezing','breathless','shortness of breath','inhaler','difficulty breathing','respiratory'], emoji:'💨', type:'chronic', description:'A chronic lung condition where airways become inflamed and narrowed, making breathing difficult. Episodes (attacks) can be triggered by various factors.', symptoms:['Wheezing (whistling sound when breathing)','Shortness of breath','Chest tightness','Coughing especially at night','Trouble sleeping due to breathing'], causes:['Allergens — dust, pollen, pet dander','Air pollution and smoke','Exercise-induced asthma','Cold air','Respiratory infections','Stress'], homecare:['Use prescribed inhalers as directed','Identify and avoid your triggers','Keep bedroom dust-free','Do not smoke and avoid secondhand smoke','Breathing exercises (pursed-lip breathing)'], whenToSeeDoctor:'Frequent attacks, inhaler not relieving symptoms, blue lips or fingernails, or struggling to speak during an attack — go to emergency.', urgency:'high' },

  { name:'Migraine', aliases:['migraine','severe headache','half head pain','throbbing headache','aura','one-sided headache','migraine attack'], emoji:'🧠', type:'chronic', description:'A neurological condition causing intense throbbing headaches, usually on one side. Often accompanied by nausea, vomiting, and sensitivity to light and sound.', symptoms:['Severe throbbing headache (often one side)','Nausea and vomiting','Sensitivity to light and sound','Visual disturbances (aura)','Dizziness','Fatigue before or after attack'], causes:['Hormonal changes','Stress and anxiety','Skipping meals or dehydration','Bright lights or loud sounds','Strong smells','Certain foods (cheese, wine, caffeine)','Lack of sleep'], homecare:['Rest in a dark quiet room','Apply cold or warm compress to head','Stay hydrated','OTC pain relievers (ibuprofen, aspirin) at onset','Keep a migraine diary to track triggers'], whenToSeeDoctor:'Migraines more than 4 times a month, sudden "thunderclap" headache, headache with fever and stiff neck, or OTC medicine stops working.', urgency:'medium' },

  { name:'Arthritis', aliases:['arthritis','joint pain','joint swelling','rheumatoid','osteoarthritis','knee pain','joint stiffness','painful joints'], emoji:'🦴', type:'chronic', description:'Inflammation of one or more joints causing pain and stiffness. Two main types: osteoarthritis (wear and tear) and rheumatoid arthritis (autoimmune).', symptoms:['Joint pain and tenderness','Stiffness especially in the morning','Swelling around joints','Reduced range of motion','Redness and warmth around joints'], causes:['Age-related wear and tear (osteoarthritis)','Autoimmune disease (rheumatoid arthritis)','Previous joint injury','Obesity','Family history','Gout or infections'], homecare:['Apply hot or cold compress to affected joints','Gentle exercises — swimming and walking are ideal','Maintain a healthy weight to reduce joint stress','OTC pain relievers and anti-inflammatories','Turmeric milk or ginger tea may help reduce inflammation'], whenToSeeDoctor:'Severe joint pain, sudden joint swelling, inability to use the joint, or fever with joint pain.', urgency:'medium' },

  { name:'Thyroid Disorder', aliases:['thyroid','hypothyroidism','hyperthyroidism','thyroid problem','low thyroid','high thyroid','thyroid disease'], emoji:'🦋', type:'chronic', description:'The thyroid gland controls metabolism. Hypothyroidism (underactive) slows the body down; hyperthyroidism (overactive) speeds it up. Both are very treatable.', symptoms:['Fatigue (hypothyroid) or nervousness (hyperthyroid)','Weight gain or unexplained weight loss','Cold intolerance or heat intolerance','Slow or fast heart rate','Hair thinning or loss','Swelling in neck','Constipation or diarrhea'], causes:['Autoimmune conditions (Hashimoto, Graves disease)','Iodine deficiency','Previous thyroid surgery or radiation','Family history','Certain medications'], homecare:['Take prescribed thyroid medication at same time every day','Eat iodine-rich foods — seafood, iodized salt, dairy','Avoid raw cruciferous vegetables in excess (hypothyroid)','Regular exercise','Get thyroid levels checked regularly'], whenToSeeDoctor:'Suspected thyroid disorder requires blood tests (TSH, T3, T4). See an endocrinologist for proper diagnosis and medication management.', urgency:'medium' },

  { name:'Anemia', aliases:['anemia','anaemia','low hemoglobin','low haemoglobin','iron deficiency','low blood','weakness','pale'], emoji:'🩸', type:'chronic', description:'A condition where you lack enough healthy red blood cells to carry adequate oxygen to your body. Iron deficiency anemia is the most common type worldwide.', symptoms:['Extreme fatigue and weakness','Pale skin and gums','Shortness of breath','Dizziness or lightheadedness','Cold hands and feet','Headache','Chest pain'], causes:['Iron deficiency (most common)','Vitamin B12 or folate deficiency','Chronic blood loss (heavy periods, ulcers)','Chronic diseases (kidney disease, cancer)','Inherited conditions (sickle cell, thalassemia)'], homecare:['Eat iron-rich foods — leafy greens, beans, meat, fortified cereals','Eat vitamin C with iron foods to improve absorption','Take iron supplements as prescribed','Avoid tea or coffee immediately after meals (blocks iron absorption)','Cook in iron vessels'], whenToSeeDoctor:'Severe fatigue, chest pain or rapid heartbeat, very pale appearance, or hemoglobin confirmed low on blood test. Diagnosis requires blood work.', urgency:'medium' },

  /* ── INFECTIOUS ── */
  { name:'Dengue', aliases:['dengue','dengue fever','breakbone fever','dengue mosquito','platelet drop','low platelet'], emoji:'🦟', type:'infectious', description:'A mosquito-borne viral disease spread by Aedes mosquitoes. Very common in India especially during and after monsoon. Can be severe in some cases.', symptoms:['Sudden high fever (104°F / 40°C)','Severe headache','Pain behind the eyes','Joint and muscle pain (breakbone fever)','Skin rash','Mild bleeding (nose, gums)','Low platelet count'], causes:['Bite of Aedes aegypti mosquito infected with dengue virus','Stagnant water breeding grounds near home','No person-to-person transmission'], homecare:['Rest and drink plenty of fluids — ORS, coconut water, juices','Paracetamol for fever — NEVER aspirin or ibuprofen','Monitor platelet count if fever persists','Use mosquito repellent and nets','Get a blood test to confirm'], whenToSeeDoctor:'Severe abdominal pain, persistent vomiting, blood in urine or stool or vomit, rapid breathing, fatigue or restlessness — go to hospital immediately. Warning signs of severe dengue.', urgency:'high' },

  { name:'Typhoid', aliases:['typhoid','typhoid fever','enteric fever','salmonella','typhoid infection'], emoji:'🌡️', type:'infectious', description:'A bacterial infection caused by Salmonella typhi, usually spread through contaminated food and water. Common in areas with poor sanitation. Treatable with antibiotics.', symptoms:['Prolonged high fever gradually rising','Weakness and fatigue','Stomach pain','Headache','Loss of appetite','Constipation or diarrhea','Rose-colored spots on skin (rare)'], causes:['Contaminated water or food','Poor hand hygiene','Consuming raw or undercooked food from unhygienic sources','Contact with infected person'], homecare:['Take prescribed antibiotics — do NOT stop early','Rest and drink plenty of clean boiled water','Eat easily digestible food — khichdi, banana, boiled rice','Maintain strict hand hygiene','Avoid outside food until fully recovered'], whenToSeeDoctor:'Suspected typhoid must be confirmed with a blood test. See a doctor immediately — antibiotics are required and should not be self-prescribed.', urgency:'high' },

  { name:'Malaria', aliases:['malaria','malarial fever','malaria infection','malaria mosquito','chills fever'], emoji:'🦟', type:'infectious', description:'A serious mosquito-borne disease caused by Plasmodium parasites. Transmitted by the Anopheles mosquito. Treatable if diagnosed early.', symptoms:['High fever with chills and sweating in cycles','Headache','Muscle aches','Fatigue','Nausea and vomiting','Anemia','Jaundice in severe cases'], causes:['Bite of infected Anopheles mosquito','No person-to-person transmission','More common in tropical and subtropical regions'], homecare:['Take prescribed antimalarial drugs — complete the course','Rest and drink plenty of fluids','Take paracetamol for fever (not aspirin or ibuprofen)','Sleep under mosquito nets','Use mosquito repellents'], whenToSeeDoctor:'Suspected malaria requires immediate blood test. Severe malaria with confusion, seizures, difficulty breathing, or jaundice is a medical emergency.', urgency:'high' },

  { name:'Chickenpox', aliases:['chickenpox','chicken pox','varicella','itchy blisters','pox','blister rash'], emoji:'🔴', type:'infectious', description:'A highly contagious viral infection causing an itchy blister-like rash. Most common in children but can be severe in adults. Usually resolves in 1-2 weeks.', symptoms:['Itchy red spots that blister and then crust over','Rash starting on face, chest, and back then spreading','Fever','Fatigue','Loss of appetite','Headache'], causes:['Varicella-zoster virus','Highly contagious — spreads through air and direct contact','A person is contagious from 1-2 days before rash until all blisters crust over'], homecare:['Calamine lotion on blisters to reduce itching','Trim fingernails and avoid scratching to prevent scars','Cool baths with baking soda or oatmeal','Paracetamol for fever — NEVER aspirin in children','Stay isolated until all blisters have crusted'], whenToSeeDoctor:'High fever, blisters in eyes or genitals, signs of bacterial infection (redness, warmth, pus around blisters), confusion, or stiff neck.', urgency:'medium' },

  { name:'COVID-19', aliases:['covid','covid-19','coronavirus','corona virus','corona','covid infection'], emoji:'🦠', type:'infectious', description:'An infectious disease caused by the SARS-CoV-2 coronavirus. Symptoms range from mild cold-like illness to severe pneumonia. Most people recover fully.', symptoms:['Fever and chills','Dry cough','Fatigue','Loss of taste or smell','Sore throat','Headache','Muscle aches','Shortness of breath (severe cases)'], causes:['Respiratory droplets from infected person','Close contact without mask','Touching contaminated surfaces then touching face','More severe in elderly and those with pre-existing conditions'], homecare:['Isolate immediately to prevent spread','Rest and drink plenty of fluids','Paracetamol for fever and body aches','Monitor oxygen levels with pulse oximeter if available','Ventilate room well'], whenToSeeDoctor:'Difficulty breathing, persistent chest pain, confusion, inability to wake or stay awake, or oxygen saturation below 94%. These require emergency care.', urgency:'high' },

  { name:'Measles', aliases:['measles','rubeola','koplik spots','measles rash'], emoji:'🔴', type:'infectious', description:'A highly contagious viral infection preventable by vaccination. Causes a characteristic red rash. Serious complications can occur especially in children.', symptoms:['High fever','Cough, runny nose, and red eyes (appear first)','Koplik spots (small white spots inside mouth)','Red blotchy rash spreading from face downward','Sensitivity to light'], causes:['Measles virus (highly contagious)','Spreads through air when infected person coughs or sneezes','Unvaccinated individuals are at high risk'], homecare:['Rest and drink plenty of fluids','Paracetamol for fever','Vitamin A supplements as recommended by doctor','Keep room dimly lit if eyes are sensitive','Isolate from unvaccinated people'], whenToSeeDoctor:'Difficulty breathing, seizures, confusion, ear pain, or severe eye infection. Measles can cause pneumonia and brain inflammation.', urgency:'high' },

  { name:'Hepatitis', aliases:['hepatitis','liver infection','hepatitis a','hepatitis b','hepatitis c','jaundice liver','liver disease'], emoji:'🍋', type:'infectious', description:'Inflammation of the liver caused by viruses (A, B, C, D, E), alcohol, or other causes. Hepatitis A and E are food/water-borne; B and C are blood/sexual contact.', symptoms:['Jaundice (yellow skin and eyes)','Dark urine','Pale stools','Fatigue','Nausea and vomiting','Abdominal pain (upper right)','Fever (in acute hepatitis)'], causes:['Hepatitis A and E: contaminated food or water','Hepatitis B and C: blood contact, unprotected sex, sharing needles','Alcohol abuse','Certain medications or toxins'], homecare:['Rest and avoid strenuous activity','Eat a balanced low-fat diet','Avoid alcohol completely','Take prescribed medications','Stay hydrated','Avoid spreading to others through good hygiene'], whenToSeeDoctor:'Suspected hepatitis requires blood tests. Yellow eyes or skin, dark urine, or abdominal pain warrant immediate medical evaluation.', urgency:'high' },

  /* ── MENTAL HEALTH ── */
  { name:'Anxiety', aliases:['anxiety','stress','panic attack','worry','nervousness','mental stress','overthinking','panic','fear','anxious'], emoji:'😰', type:'mental', description:'A mental health condition characterized by persistent worry, fear, or unease. One of the most common mental health conditions globally and very treatable.', symptoms:['Excessive worry and fear','Rapid heartbeat (palpitations)','Sweating and trembling','Shortness of breath','Difficulty concentrating','Insomnia','Irritability','Headaches'], causes:['Stress and major life events','Trauma or past experiences','Genetics and brain chemistry','Certain medical conditions','Caffeine and alcohol','Social pressure'], homecare:['Deep breathing exercises (4-7-8 breathing)','Regular physical exercise (30 min daily)','Limit caffeine and alcohol','Maintain a sleep routine','Talk to a trusted friend or family member','Mindfulness and meditation apps can help'], whenToSeeDoctor:'Anxiety interfering with daily life, frequent panic attacks, thoughts of self-harm, or symptoms lasting more than 6 months. Therapy (CBT) and medication are highly effective.', urgency:'medium' },

  { name:'Depression', aliases:['depression','depressed','sadness','feeling low','hopeless','no motivation','empty feeling','mental health'], emoji:'😔', type:'mental', description:'A common and serious mental health condition causing persistent feelings of sadness and loss of interest. It affects how you feel, think, and handle daily activities.', symptoms:['Persistent sad or empty feeling','Loss of interest in activities once enjoyed','Fatigue and decreased energy','Changes in appetite and weight','Sleep problems (insomnia or oversleeping)','Difficulty concentrating','Feelings of worthlessness or guilt','Thoughts of death or suicide'], causes:['Brain chemistry imbalance','Hormonal changes','Genetic factors','Traumatic or stressful life events','Chronic illness or pain','Substance abuse'], homecare:['Maintain a daily routine','Get regular exercise — even short walks help','Connect with friends and family','Avoid alcohol','Get adequate sleep','Seek professional support — talking to a therapist helps enormously'], whenToSeeDoctor:'Thoughts of self-harm or suicide — seek immediate help. Also see a doctor if depression is severe, lasting more than 2 weeks, or interfering with daily function.', urgency:'high' },

  { name:'Insomnia', aliases:['insomnia','sleep problem','cant sleep','difficulty sleeping','sleeplessness','poor sleep','sleep disorder'], emoji:'😴', type:'mental', description:'Difficulty falling asleep or staying asleep that affects daytime functioning. Affects about 30% of adults. Usually treatable with lifestyle changes.', symptoms:['Difficulty falling asleep at night','Waking during the night','Waking too early','Not feeling rested after sleep','Daytime tiredness','Irritability and mood problems','Difficulty concentrating'], causes:['Stress and anxiety','Poor sleep habits (irregular schedule, screen use)','Caffeine, nicotine, or alcohol','Certain medications','Pain or medical conditions','Shift work or jet lag'], homecare:['Go to bed and wake at the same time every day','Avoid screens 1 hour before bed','Keep bedroom cool, dark, and quiet','Avoid caffeine after 2 PM','Do not lie awake in bed — get up if unable to sleep after 20 min','Try relaxation techniques — deep breathing, progressive muscle relaxation'], whenToSeeDoctor:'Insomnia lasting more than 1 month, associated with depression or anxiety, significantly affecting work or relationships, or if you suspect sleep apnea.', urgency:'low' },

  /* ── LIFESTYLE ── */
  { name:'Obesity', aliases:['obesity','overweight','weight problem','fat','bmi high','gaining weight'], emoji:'⚖️', type:'lifestyle', description:'A complex condition involving excess body fat that increases the risk of health problems. BMI above 30 is classified as obese. Highly preventable and manageable.', symptoms:['Excess body weight and fat','Shortness of breath with activity','Snoring or sleep apnea','Back and joint pain','Fatigue','Excessive sweating'], causes:['Consuming more calories than burned','Sedentary lifestyle','Genetics and family history','Certain medications','Hormonal disorders (thyroid, PCOS)','Poor sleep'], homecare:['Create a calorie deficit — reduce portions and choose healthy foods','Exercise at least 30 minutes most days','Drink water instead of sugary drinks','Eat more vegetables, fruits, and whole grains','Track food intake','Get enough sleep (poor sleep increases hunger hormones)'], whenToSeeDoctor:'BMI above 30, obesity-related health problems (diabetes, hypertension, sleep apnea), or inability to lose weight despite lifestyle changes. Medical supervision is recommended.', urgency:'medium' },

  { name:'PCOS', aliases:['pcos','polycystic ovary','polycystic ovarian syndrome','irregular periods','hormonal imbalance','pco','ovarian cyst'], emoji:'🌸', type:'lifestyle', description:'Polycystic Ovary Syndrome is a hormonal disorder common among women of reproductive age. It affects menstrual cycles, fertility, and metabolism.', symptoms:['Irregular or absent menstrual periods','Excess hair on face or body (hirsutism)','Acne and oily skin','Hair thinning or loss on scalp','Weight gain (especially around abdomen)','Difficulty getting pregnant','Small cysts on ovaries (on ultrasound)'], causes:['Excess insulin and insulin resistance','Low-grade inflammation','Genetics and family history','Excess androgen hormones'], homecare:['Maintain a healthy weight — even 5-10% weight loss improves symptoms','Follow a low glycemic diet (avoid refined carbs and sugar)','Exercise regularly','Manage stress','Track your menstrual cycle'], whenToSeeDoctor:'Irregular periods, difficulty conceiving, or symptoms of PCOS. Diagnosis requires blood tests and ultrasound. An endocrinologist or gynecologist can help manage this effectively.', urgency:'medium' },

  { name:'Dehydration', aliases:['dehydration','not drinking water','thirst','dry mouth','dark urine','dehydrated'], emoji:'💧', type:'common', description:'Dehydration occurs when your body loses more fluid than you take in. Even mild dehydration affects energy and mood. Very common especially in hot climates.', symptoms:['Extreme thirst','Dark yellow or brown urine','Dry mouth and lips','Fatigue and dizziness','Headache','Decreased urination','Dry skin'], causes:['Not drinking enough water','Excessive sweating in heat or during exercise','Diarrhea or vomiting','Fever','Certain medications (diuretics)'], homecare:['Drink water regularly throughout the day — aim for 8-10 glasses','ORS for severe dehydration','Eat foods with high water content — cucumber, watermelon, oranges','Avoid excessive caffeine and alcohol','Drink more in hot weather or when exercising'], whenToSeeDoctor:'No urination for 8+ hours, sunken eyes, rapid heartbeat, confusion, or if unable to keep fluids down. Severe dehydration requires IV fluids.', urgency:'medium' },

  { name:'Heat Stroke & Heat Exhaustion', aliases:['heat stroke','heat exhaustion','sunstroke','sun stroke','overheating','heat illness'], emoji:'☀️', type:'emergency', description:'Heat stroke is a life-threatening emergency where the body overheats (above 104°F/40°C). Heat exhaustion is the milder precursor. Both require immediate action.', symptoms:['High body temperature (heat stroke: above 104°F)','Hot and red dry skin (no sweating in heat stroke)','Heavy sweating and pale skin (heat exhaustion)','Rapid heartbeat','Confusion or unconsciousness (heat stroke)','Nausea and vomiting','Headache and dizziness'], causes:['Exposure to high temperatures','Physical exertion in hot weather','Insufficient fluid intake','Wearing heavy clothing in heat','Working outdoors in summer'], homecare:['MOVE to a cool shaded area immediately','Remove excess clothing','Apply cool water to skin, especially neck, armpits, and groin','Fan the person','Drink cool water if conscious and alert','Use cool wet cloths or ice packs'], whenToSeeDoctor:'Heat stroke is a MEDICAL EMERGENCY — call ambulance immediately. Unconsciousness, confusion, or high fever in hot conditions requires immediate emergency care.', urgency:'high' },

  { name:'Urinary Tract Infection (UTI)', aliases:['uti','urinary tract infection','urine infection','burning urination','frequent urination','bladder infection','cystitis'], emoji:'🔥', type:'common', description:'An infection in any part of the urinary system. More common in women. Usually affects the bladder (cystitis) but can spread to kidneys if untreated.', symptoms:['Burning sensation when urinating','Frequent urge to urinate','Cloudy or foul-smelling urine','Pelvic pain in women','Blood in urine (pinkish or red)','Low-grade fever'], causes:['Bacteria (usually E. coli) entering the urinary tract','Poor hygiene','Dehydration','Holding urine for too long','Sexual activity','Pregnancy'], homecare:['Drink plenty of water to flush bacteria out','Urinate frequently — do not hold it in','Wipe from front to back after toilet','Wear cotton underwear and loose clothing','Cranberry juice may help prevent (not treat) UTIs'], whenToSeeDoctor:'UTI symptoms lasting more than 2 days, high fever, back or flank pain (possible kidney infection), blood in urine, or UTI during pregnancy — always needs medical treatment.', urgency:'medium' },

  { name:'Skin Rash', aliases:['rash','skin rash','dermatitis','eczema','skin irritation','itchy skin','red skin','skin allergy'], emoji:'🔴', type:'common', description:'A rash is a change in the skin that causes redness, itching, or inflammation. Can be caused by allergies, infections, heat, or skin conditions.', symptoms:['Redness or discoloration of skin','Itching or burning sensation','Bumps, blisters, or patches','Swelling','Dry, flaky, or scaly skin','Warmth in the affected area'], causes:['Allergic reaction to food, plants, or chemicals','Eczema (atopic dermatitis)','Heat rash (prickly heat)','Contact dermatitis (soap, detergent, jewelry)','Viral or bacterial infections','Psoriasis'], homecare:['Avoid the suspected cause (soap, food, fabric)','Apply calamine lotion or hydrocortisone cream for itching','Use a cold compress for relief','Keep the area clean and dry','Wear loose, breathable cotton clothing','Moisturize dry skin regularly'], whenToSeeDoctor:'Rash spreading rapidly, blisters, peeling skin, difficulty breathing, rash with fever, or rash not improving after 1 week.', urgency:'medium' },

  { name:'Toothache', aliases:['toothache','tooth pain','dental pain','tooth decay','cavity','gum pain','wisdom tooth'], emoji:'🦷', type:'common', description:'Pain in or around a tooth, usually caused by tooth decay, infection, or gum disease. Can range from mild discomfort to severe throbbing pain.', symptoms:['Sharp, throbbing, or constant tooth pain','Pain when biting or chewing','Sensitivity to hot and cold','Swelling around the tooth or jaw','Fever (if infection is present)','Headache'], causes:['Tooth decay (cavity)','Cracked or chipped tooth','Infected tooth (abscess)','Gum disease','Grinding teeth (bruxism)','Impacted wisdom tooth'], homecare:['Rinse with warm salt water','Apply clove oil with a cotton ball to the area (natural anesthetic)','Take OTC pain relievers (ibuprofen works best for dental pain)','Apply ice pack on cheek','Avoid very hot, cold, or sweet foods'], whenToSeeDoctor:'Severe pain, swelling of face or jaw, fever, difficulty swallowing or breathing, or if pain persists more than 1-2 days. Dental infections can be dangerous if untreated.', urgency:'medium' },

  { name:'Eye Strain', aliases:['eye strain','digital eye strain','tired eyes','eye fatigue','blurry vision','eye pain from screen','computer vision'], emoji:'👁️', type:'lifestyle', description:'Discomfort in the eyes after intense use, especially from screens. Very common in the digital age. Usually temporary and resolves with rest.', symptoms:['Sore, tired, or burning eyes','Blurred or double vision','Headache','Difficulty concentrating','Dry or watery eyes','Neck and shoulder pain'], causes:['Prolonged screen use (computer, phone, TV)','Poor lighting','Incorrect screen distance or angle','Uncorrected vision problems','Dry air from air conditioning'], homecare:['Follow the 20-20-20 rule: every 20 min, look at something 20 feet away for 20 seconds','Adjust screen brightness and font size','Position screen at arm\'s length','Use artificial tear drops for dry eyes','Take regular breaks from screens'], whenToSeeDoctor:'Persistent blurred vision, double vision, sudden vision changes, eye pain with redness, or if headaches are severe and recurring. Get regular eye checkups.', urgency:'low' },

  { name:'Vitamin D Deficiency', aliases:['vitamin d deficiency','low vitamin d','vitamin d','bone pain','sun vitamin'], emoji:'☀️', type:'lifestyle', description:'Vitamin D deficiency is extremely common especially in people with indoor lifestyles. It affects bones, immune function, and mood. Easily corrected.', symptoms:['Bone pain and tenderness','Muscle weakness and fatigue','Frequent infections','Depression or low mood','Hair loss','Slow wound healing'], causes:['Insufficient sun exposure','Darker skin (requires more sun exposure)','Indoor lifestyle','Poor diet (few vitamin D-rich foods)','Obesity (vitamin D gets stored in fat)','Older age (skin produces less vitamin D)'], homecare:['Spend 15-30 minutes in morning sunlight daily','Eat vitamin D-rich foods — fatty fish, egg yolks, fortified dairy and cereals','Take vitamin D3 supplements as prescribed','Combine with calcium and magnesium for bone health'], whenToSeeDoctor:'Suspected deficiency requires a blood test (25-OH Vitamin D). Severe deficiency needs prescription-strength supplements.', urgency:'low' },

  { name:'Kidney Stones', aliases:['kidney stones','kidney stone','renal calculi','nephrolithiasis','stone in kidney','urinary stone','severe back pain urine'], emoji:'🪨', type:'common', description:'Hard deposits of minerals and salts that form inside the kidneys. Can cause severe pain when passing through the urinary tract. Very common, especially in men.', symptoms:['Severe, sharp pain in the back, side, or lower abdomen','Pain that comes in waves','Pain during urination','Pink, red, or brown urine','Nausea and vomiting','Frequent urge to urinate','Cloudy or foul-smelling urine'], causes:['Dehydration and not drinking enough water','High salt or protein diet','Family history','Obesity','Certain medications or supplements (calcium, vitamin C excess)'], homecare:['Drink at least 2-3 liters of water daily','Reduce salt and animal protein in diet','Lemon juice in water increases citrate (prevents stone formation)','Take prescribed pain relievers','Strain urine to catch passed stone for analysis'], whenToSeeDoctor:'Severe pain, fever with pain (sign of infection), inability to pass urine, or if stone does not pass after several days. Large stones may need medical removal.', urgency:'high' },

  { name:'Sinusitis', aliases:['sinusitis','sinus','sinus infection','sinus pain','facial pain','sinus headache','blocked sinus','nasal congestion'], emoji:'👃', type:'common', description:'Inflammation of the sinuses (air-filled cavities in the skull) usually caused by infection or allergy. The face, forehead, and nose can be painful and congested.', symptoms:['Pain and pressure in face (cheeks, forehead, around eyes)','Nasal congestion and discharge (thick yellow or green)','Loss of smell and taste','Headache','Fatigue','Sore throat from drainage','Cough'], causes:['Viral infection (most common) — often follows a cold','Bacterial infection','Allergies','Nasal polyps or deviated septum','Dry air'], homecare:['Steam inhalation 2-3 times daily','Nasal saline irrigation (Neti pot or nasal spray)','Stay well hydrated','Use a humidifier','Apply warm compress over sinuses','Rest and avoid cold air'], whenToSeeDoctor:'Symptoms lasting more than 10 days without improvement, high fever, severe headache, stiff neck, vision changes, or swelling around eyes.', urgency:'low' },

  { name:'Mumps', aliases:['mumps','swollen cheeks','swollen glands','parotid gland swelling'], emoji:'🏥', type:'infectious', description:'A contagious viral infection that mainly affects the salivary glands, causing characteristic swollen, puffy cheeks. Preventable by MMR vaccination.', symptoms:['Swollen and painful salivary glands (puffy cheeks and jaw)','Fever','Headache','Muscle aches','Loss of appetite','Difficulty chewing and swallowing'], causes:['Mumps virus (paramyxovirus)','Spreads through respiratory droplets and saliva','Unvaccinated individuals at high risk'], homecare:['Rest and drink plenty of fluids','Soft foods that are easy to chew','Cold or warm packs on swollen glands','Paracetamol for pain and fever','Gargle with warm salt water for throat discomfort'], whenToSeeDoctor:'High fever, severe headache with stiff neck (meningitis), testicular pain and swelling in males, or hearing loss after mumps.', urgency:'medium' },

  { name:'Jaundice', aliases:['jaundice','yellow eyes','yellow skin','yellowish','yellowing of skin'], emoji:'🍋', type:'common', description:'Yellowing of the skin and whites of the eyes caused by high bilirubin levels. It is a symptom of an underlying condition, not a disease itself.', symptoms:['Yellow discoloration of skin and eyes','Dark yellow or brown urine','Pale or clay-colored stools','Itching','Fatigue','Abdominal pain','Nausea'], causes:['Liver disease (hepatitis, cirrhosis)','Bile duct obstruction (gallstones)','Hemolysis (destruction of red blood cells)','Newborn jaundice (physiological — common and usually benign)','Certain medications'], homecare:['Rest completely','Avoid alcohol completely','Eat a light, low-fat diet','Stay hydrated','Avoid heavy or spicy food','Light exposure for newborn jaundice (under doctor supervision)'], whenToSeeDoctor:'Jaundice always requires medical evaluation to find the underlying cause. See a doctor promptly — especially if accompanied by fever, abdominal pain, or confusion.', urgency:'high' },

  { name:'Cholesterol (High)', aliases:['high cholesterol','cholesterol','hypercholesterolemia','lipid problem','bad cholesterol','ldl','hdl'], emoji:'🫀', type:'lifestyle', description:'High cholesterol means you have too much of a fatty substance in your blood. Over time it can lead to blocked arteries and heart disease. Usually has no symptoms.', symptoms:['Usually no symptoms','Chest pain (if arteries are blocked)','Xanthelasma (yellowish deposits around eyes) in extreme cases','Detected only through blood test'], causes:['Unhealthy diet (high in saturated and trans fats)','Sedentary lifestyle','Obesity','Smoking','Family history','Diabetes and hypothyroidism'], homecare:['Reduce saturated fats (butter, red meat, full-fat dairy)','Eat more fiber — oats, beans, fruits, vegetables','Exercise 30 min most days','Quit smoking','Lose excess weight','Eat healthy fats — olive oil, nuts, avocado'], whenToSeeDoctor:'Get cholesterol checked every 5 years from age 20. If levels are high, a doctor will recommend diet changes and possibly medication (statins).', urgency:'medium' },

  { name:'Vertigo', aliases:['vertigo','dizziness','spinning sensation','balance problem','dizzy','lightheaded'], emoji:'🌀', type:'common', description:'A sensation of feeling off balance or that the world is spinning around you. Often caused by an inner ear problem. Usually not serious but very disorienting.', symptoms:['Sensation of spinning or movement when still','Loss of balance','Nausea and vomiting','Headache','Sweating','Ringing in the ears (tinnitus)'], causes:['BPPV (benign paroxysmal positional vertigo — most common)','Meniere\'s disease (inner ear fluid)','Labyrinthitis (inner ear infection)','Migraine','Head injury'], homecare:['Sit or lie down immediately when dizzy to avoid falling','Move slowly — especially when getting up','Epley maneuver (for BPPV — a series of head movements)','Avoid caffeine and alcohol','Stay well hydrated'], whenToSeeDoctor:'Vertigo with chest pain, difficulty speaking, double vision, weakness or numbness, or sudden severe headache — these may indicate stroke. Also see doctor if vertigo is persistent or recurrent.', urgency:'medium' },
];

/* ── SEARCH FUNCTION ── */
function searchOfflineDB(query) {
  const q = query.toLowerCase().trim();
  if (!q || q.length < 2) return null;

  let best = null;
  let bestScore = 0;

  for (const d of DISEASE_DB) {
    let score = 0;
    const nameLower = d.name.toLowerCase();

    // Exact name match — highest priority
    if (nameLower === q) { score = 100; }
    // Name starts with query
    else if (nameLower.startsWith(q)) { score = 80; }
    // Name contains query
    else if (nameLower.includes(q)) { score = 60; }
    else {
      // Check aliases
      for (const alias of d.aliases) {
        if (alias === q) { score = Math.max(score, 90); break; }
        if (alias.startsWith(q)) { score = Math.max(score, 70); }
        else if (alias.includes(q)) { score = Math.max(score, 50); }
        else if (q.includes(alias) && alias.length > 3) { score = Math.max(score, 40); }
      }
    }

    if (score > bestScore) { bestScore = score; best = d; }
  }

  return bestScore >= 40 ? best : null;
}
